export const FETCH_USER = "FETCH_USER";
export const FETCH_PRODUCTS_LIST = "FETCH_PRODUCT_LIST";
export const REDEEM_PRODUCT = "REDEEM_PRODUCT";
export const LOADING = "LOADING";
export const SET_FILTER_BY = "SET_FILTER_BY";
export const PRODUCTS_FILTERED = "PRODUCTS_FILTERED";
export const GET_PRODUCT_ID_SELECTED = "GET_PRODUCT_SELECTED";
